### ISSUE TITLE
is it still getting updating?

### ISSUE THREAD

**Issue by maciejszulia** [Asteria5675/BetterDiscordThemes#9]
Not gonna lie, my favourite theme

**Comment by headpatspls** [comment]
same here please update

**Comment by notthefoxx** [comment]
They are not really active even on BetterDiscord server. It might never be updated I guess. We can ask x6r, maybe they still gonna maintain it.

**Comment by bolomonk** [comment]
dusk to dawn was amazing yeah

would love them to update

**Comment by notthefoxx** [comment]
It would never be updated, I asked x6r about it.
`
dusk to dawn was abandoned by asteria (dusk to dawn creator) a long time ago. currently there are no plans for it to be updated.
`

**Comment by maciejszulia** [comment]
r.i.p.
